#%RAML 1.0 SecurityScheme
description: |
  This API supports Pass Through Authentication.
type: Pass Through
describedBy: 
  headers: 
    X-Api-Key: 
      displayName: API Key
      description: API authentication header
      example: apikey
