#%RAML 1.0 NamedExample
value:
  key_transaction:
    id: 1
    name: key anme
    transaction_name: string
    application_summaries:
      response_time: 0.06145
      throughput: 451.2
      error_rate: 11.2
      apdex_target: 0.8
      apdex_score: 0.5
    end_user_summaries:
      response_time: 101.2
      throughput: 412.2
      apdex_target: 0.8
      apdex_score: 0.5
    links:
      application: 123456