#%RAML 1.0 NamedExample
value:
  server:
    id: 1
    account_id: 1
    display_name: some string
    host: some string
    reporting: true
    last_reported_at: time
    summaries:
      cpu: 1
      cpu_stolen: 1
      disk_io: 1
      memory: 1
      memory_used: 1
      memory_total: 1
      fullest_disk: 1
      fullest_disk_free: 1