#%RAML 1.0 NamedExample
value:
  application:
    id: 3961789
    name: Core Services (dev)
    language: nodejs
    health_status: gray
    reporting: false
    settings:
      app_apdex_threshold: 0.02
      end_user_apdex_threshold: 7
      enable_real_user_monitoring: true
      use_server_side_config: false
    links:
      application_instances: []
      alert_policy: 63721
      servers: []
      application_hosts: []