#%RAML 1.0 NamedExample
application_hosts:
  - id: 89809888
    application_name: Authentication Server (production)
    host: authentication-server-i-00b275e78ba0b12ff
    language: nodejs
    health_status: green
    application_summary:
      response_time: 27.1
      throughput: 1520
      error_rate: 0
      apdex_score: 0.91
      instance_count: 1
    links:
      application: 89804076
      application_instances:
        - 89809889
      server: 89809821
  - id: 89809925
    application_name: Authentication Server (production)
    host: authentication-server-i-01643f4bbbf78c68a
    language: nodejs
    health_status: green
    application_summary:
      response_time: 27
      throughput: 1580
      error_rate: 0
      apdex_score: 0.91
      instance_count: 1
    links:
      application: 89804076
      application_instances:
        - 89809926
      server: 89809878
