#%RAML 1.0 NamedExample
value:
  application_instance:
    id: 1
    application_name: some string
    host: some string
    port: 1
    language: 1
    health_status: some string
    application_summaries:
      response_time: 1
      throughput: 1
      error_rate: 1
      apdex_score: 1
    end_user_summaries:
      response_time: 1
      throughput: 1
      apdex_score: 1
    links:
      application: 1
      application_host: 1
      server: 1