#%RAML 1.0 NamedExample
application_instances:
  - id: 89809759
    application_name: Authentication Server (production)
    host: authentication-server-i-070e335f61f217ea0
    language: nodejs
    health_status: green
    application_summary:
      response_time: 30
      throughput: 1440
      error_rate: 0
      apdex_score: 0.91
      instance_count: 1
    links:
      application: 89804076
      application_host: 89809758
      server: 89809704
  - id: 89809812
    application_name: Authentication Server (production)
    host: authentication-server-i-08af1e73a17bef8cc
    language: nodejs
    health_status: green
    application_summary:
      response_time: 32.5
      throughput: 1390
      error_rate: 0
      apdex_score: 0.89
      instance_count: 1