#%RAML 1.0 NamedExample
servers:
  - id: 7497120
    account_id: 205337
    name: new-nexus-master
    host: new-nexus-master
    health_status: green
    reporting: true
    last_reported_at: '2018-02-07T02:39:32+00:00'
    summary:
      cpu: 6.68
      cpu_stolen: 0.01
      disk_io: 5.23
      memory: 8.68
      memory_used: 5866782720
      memory_total: 67559751680
      fullest_disk: 72.6
      fullest_disk_free: 579855000000
    links:
      alert_policy: 63719
  - id: 7497121
    account_id: 205337
    name: new-nexus-proxy
    host: new-nexus-proxy
    health_status: green
    reporting: true
    last_reported_at: '2018-02-07T02:39:57+00:00'
    summary:
      cpu: 5.56
      cpu_stolen: 0.04
      disk_io: 1.23
      memory: 64
      memory_used: 5024776192
      memory_total: 7846494208
      fullest_disk: 76.3
      fullest_disk_free: 501083000000
    links:
      alert_policy: 63719